// proto/note/note.proto
// 笔记服务 Protobuf 定义。
// 定义 NoteService 的 RPC 方法及请求/响应消息结构。
// 生成 Go 桩代码：make proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: note/note.proto

package notepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateNoteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ImageUrls     []string               `protobuf:"bytes,4,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"` // 图片 URL 列表
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`                            // 标签列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNoteReq) Reset() {
	*x = CreateNoteReq{}
	mi := &file_note_note_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNoteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoteReq) ProtoMessage() {}

func (x *CreateNoteReq) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoteReq.ProtoReflect.Descriptor instead.
func (*CreateNoteReq) Descriptor() ([]byte, []int) {
	return file_note_note_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNoteReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateNoteReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateNoteReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateNoteReq) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *CreateNoteReq) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateNoteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        int64                  `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"` // 新创建的笔记 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNoteResp) Reset() {
	*x = CreateNoteResp{}
	mi := &file_note_note_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNoteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoteResp) ProtoMessage() {}

func (x *CreateNoteResp) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoteResp.ProtoReflect.Descriptor instead.
func (*CreateNoteResp) Descriptor() ([]byte, []int) {
	return file_note_note_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNoteResp) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

type GetNoteDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        int64                  `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoteDetailReq) Reset() {
	*x = GetNoteDetailReq{}
	mi := &file_note_note_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoteDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteDetailReq) ProtoMessage() {}

func (x *GetNoteDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteDetailReq.ProtoReflect.Descriptor instead.
func (*GetNoteDetailReq) Descriptor() ([]byte, []int) {
	return file_note_note_proto_rawDescGZIP(), []int{2}
}

func (x *GetNoteDetailReq) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

type NoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ImageUrls     []string               `protobuf:"bytes,5,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteResponse) Reset() {
	*x = NoteResponse{}
	mi := &file_note_note_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteResponse) ProtoMessage() {}

func (x *NoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteResponse.ProtoReflect.Descriptor instead.
func (*NoteResponse) Descriptor() ([]byte, []int) {
	return file_note_note_proto_rawDescGZIP(), []int{3}
}

func (x *NoteResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NoteResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *NoteResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NoteResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NoteResponse) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *NoteResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *NoteResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_note_note_proto protoreflect.FileDescriptor

const file_note_note_proto_rawDesc = "" +
	"\n" +
	"\x0fnote/note.proto\x12\x04note\"\x8b\x01\n" +
	"\rCreateNoteReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"image_urls\x18\x04 \x03(\tR\timageUrls\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\")\n" +
	"\x0eCreateNoteResp\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x03R\x06noteId\"+\n" +
	"\x10GetNoteDetailReq\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x03R\x06noteId\"\xb9\x01\n" +
	"\fNoteResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"image_urls\x18\x05 \x03(\tR\timageUrls\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt2\x83\x01\n" +
	"\vNoteService\x127\n" +
	"\n" +
	"CreateNote\x12\x13.note.CreateNoteReq\x1a\x14.note.CreateNoteResp\x12;\n" +
	"\rGetNoteDetail\x12\x16.note.GetNoteDetailReq\x1a\x12.note.NoteResponseB\x1dZ\x1bxys-clone/proto/note;notepbb\x06proto3"

var (
	file_note_note_proto_rawDescOnce sync.Once
	file_note_note_proto_rawDescData []byte
)

func file_note_note_proto_rawDescGZIP() []byte {
	file_note_note_proto_rawDescOnce.Do(func() {
		file_note_note_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_note_note_proto_rawDesc), len(file_note_note_proto_rawDesc)))
	})
	return file_note_note_proto_rawDescData
}

var file_note_note_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_note_note_proto_goTypes = []any{
	(*CreateNoteReq)(nil),    // 0: note.CreateNoteReq
	(*CreateNoteResp)(nil),   // 1: note.CreateNoteResp
	(*GetNoteDetailReq)(nil), // 2: note.GetNoteDetailReq
	(*NoteResponse)(nil),     // 3: note.NoteResponse
}
var file_note_note_proto_depIdxs = []int32{
	0, // 0: note.NoteService.CreateNote:input_type -> note.CreateNoteReq
	2, // 1: note.NoteService.GetNoteDetail:input_type -> note.GetNoteDetailReq
	1, // 2: note.NoteService.CreateNote:output_type -> note.CreateNoteResp
	3, // 3: note.NoteService.GetNoteDetail:output_type -> note.NoteResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_note_note_proto_init() }
func file_note_note_proto_init() {
	if File_note_note_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_note_note_proto_rawDesc), len(file_note_note_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_note_note_proto_goTypes,
		DependencyIndexes: file_note_note_proto_depIdxs,
		MessageInfos:      file_note_note_proto_msgTypes,
	}.Build()
	File_note_note_proto = out.File
	file_note_note_proto_goTypes = nil
	file_note_note_proto_depIdxs = nil
}
