// proto/feed/feed.proto
// Feed 服务 Protobuf 定义。
// 提供用户信息流接口（推拉结合）。
// 生成 Go 桩代码：make proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: feed/feed.proto

package feedpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserFeedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                         // 页码，从 1 开始
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页条数，默认 10
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFeedReq) Reset() {
	*x = GetUserFeedReq{}
	mi := &file_feed_feed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFeedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFeedReq) ProtoMessage() {}

func (x *GetUserFeedReq) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFeedReq.ProtoReflect.Descriptor instead.
func (*GetUserFeedReq) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserFeedReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserFeedReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserFeedReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetUserFeedResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FeedItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总数（-1 表示不精确）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFeedResp) Reset() {
	*x = GetUserFeedResp{}
	mi := &file_feed_feed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFeedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFeedResp) ProtoMessage() {}

func (x *GetUserFeedResp) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFeedResp.ProtoReflect.Descriptor instead.
func (*GetUserFeedResp) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserFeedResp) GetItems() []*FeedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetUserFeedResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type FeedItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        int64                  `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	AuthorId      int64                  `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	AuthorName    string                 `protobuf:"bytes,3,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	AuthorAvatar  string                 `protobuf:"bytes,4,opt,name=author_avatar,json=authorAvatar,proto3" json:"author_avatar,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	ImageUrls     []string               `protobuf:"bytes,7,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	Tags          []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 笔记创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedItem) Reset() {
	*x = FeedItem{}
	mi := &file_feed_feed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedItem) ProtoMessage() {}

func (x *FeedItem) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedItem.ProtoReflect.Descriptor instead.
func (*FeedItem) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{2}
}

func (x *FeedItem) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *FeedItem) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *FeedItem) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *FeedItem) GetAuthorAvatar() string {
	if x != nil {
		return x.AuthorAvatar
	}
	return ""
}

func (x *FeedItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FeedItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *FeedItem) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *FeedItem) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *FeedItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_feed_feed_proto protoreflect.FileDescriptor

const file_feed_feed_proto_rawDesc = "" +
	"\n" +
	"\x0ffeed/feed.proto\x12\x04feed\"Z\n" +
	"\x0eGetUserFeedReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"M\n" +
	"\x0fGetUserFeedResp\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.feed.FeedItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x88\x02\n" +
	"\bFeedItem\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x03R\x06noteId\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\x03R\bauthorId\x12\x1f\n" +
	"\vauthor_name\x18\x03 \x01(\tR\n" +
	"authorName\x12#\n" +
	"\rauthor_avatar\x18\x04 \x01(\tR\fauthorAvatar\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"image_urls\x18\a \x03(\tR\timageUrls\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt2I\n" +
	"\vFeedService\x12:\n" +
	"\vGetUserFeed\x12\x14.feed.GetUserFeedReq\x1a\x15.feed.GetUserFeedRespB\x1dZ\x1bxys-clone/proto/feed;feedpbb\x06proto3"

var (
	file_feed_feed_proto_rawDescOnce sync.Once
	file_feed_feed_proto_rawDescData []byte
)

func file_feed_feed_proto_rawDescGZIP() []byte {
	file_feed_feed_proto_rawDescOnce.Do(func() {
		file_feed_feed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feed_feed_proto_rawDesc), len(file_feed_feed_proto_rawDesc)))
	})
	return file_feed_feed_proto_rawDescData
}

var file_feed_feed_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_feed_feed_proto_goTypes = []any{
	(*GetUserFeedReq)(nil),  // 0: feed.GetUserFeedReq
	(*GetUserFeedResp)(nil), // 1: feed.GetUserFeedResp
	(*FeedItem)(nil),        // 2: feed.FeedItem
}
var file_feed_feed_proto_depIdxs = []int32{
	2, // 0: feed.GetUserFeedResp.items:type_name -> feed.FeedItem
	0, // 1: feed.FeedService.GetUserFeed:input_type -> feed.GetUserFeedReq
	1, // 2: feed.FeedService.GetUserFeed:output_type -> feed.GetUserFeedResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_feed_feed_proto_init() }
func file_feed_feed_proto_init() {
	if File_feed_feed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feed_feed_proto_rawDesc), len(file_feed_feed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_feed_feed_proto_goTypes,
		DependencyIndexes: file_feed_feed_proto_depIdxs,
		MessageInfos:      file_feed_feed_proto_msgTypes,
	}.Build()
	File_feed_feed_proto = out.File
	file_feed_feed_proto_goTypes = nil
	file_feed_feed_proto_depIdxs = nil
}
