// proto/interaction/interaction.proto
// 互动服务 Protobuf 定义。
// 定义点赞、收藏、评论及互动汇总查询接口。
// 生成 Go 桩代码：make proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: interaction/interaction.proto

package interactionpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InteractionService_LikeNote_FullMethodName            = "/interaction.InteractionService/LikeNote"
	InteractionService_UnlikeNote_FullMethodName          = "/interaction.InteractionService/UnlikeNote"
	InteractionService_CollectNote_FullMethodName         = "/interaction.InteractionService/CollectNote"
	InteractionService_UncollectNote_FullMethodName       = "/interaction.InteractionService/UncollectNote"
	InteractionService_CommentOnNote_FullMethodName       = "/interaction.InteractionService/CommentOnNote"
	InteractionService_DeleteComment_FullMethodName       = "/interaction.InteractionService/DeleteComment"
	InteractionService_GetNoteInteractions_FullMethodName = "/interaction.InteractionService/GetNoteInteractions"
)

// InteractionServiceClient is the client API for InteractionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ──────────── 互动服务 ────────────
type InteractionServiceClient interface {
	LikeNote(ctx context.Context, in *LikeNoteReq, opts ...grpc.CallOption) (*LikeNoteResp, error)
	UnlikeNote(ctx context.Context, in *UnlikeNoteReq, opts ...grpc.CallOption) (*UnlikeNoteResp, error)
	CollectNote(ctx context.Context, in *CollectNoteReq, opts ...grpc.CallOption) (*CollectNoteResp, error)
	UncollectNote(ctx context.Context, in *UncollectNoteReq, opts ...grpc.CallOption) (*UncollectNoteResp, error)
	CommentOnNote(ctx context.Context, in *CommentOnNoteReq, opts ...grpc.CallOption) (*CommentOnNoteResp, error)
	DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error)
	GetNoteInteractions(ctx context.Context, in *GetNoteInteractionsReq, opts ...grpc.CallOption) (*GetNoteInteractionsResp, error)
}

type interactionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInteractionServiceClient(cc grpc.ClientConnInterface) InteractionServiceClient {
	return &interactionServiceClient{cc}
}

func (c *interactionServiceClient) LikeNote(ctx context.Context, in *LikeNoteReq, opts ...grpc.CallOption) (*LikeNoteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikeNoteResp)
	err := c.cc.Invoke(ctx, InteractionService_LikeNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) UnlikeNote(ctx context.Context, in *UnlikeNoteReq, opts ...grpc.CallOption) (*UnlikeNoteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlikeNoteResp)
	err := c.cc.Invoke(ctx, InteractionService_UnlikeNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) CollectNote(ctx context.Context, in *CollectNoteReq, opts ...grpc.CallOption) (*CollectNoteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectNoteResp)
	err := c.cc.Invoke(ctx, InteractionService_CollectNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) UncollectNote(ctx context.Context, in *UncollectNoteReq, opts ...grpc.CallOption) (*UncollectNoteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UncollectNoteResp)
	err := c.cc.Invoke(ctx, InteractionService_UncollectNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) CommentOnNote(ctx context.Context, in *CommentOnNoteReq, opts ...grpc.CallOption) (*CommentOnNoteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentOnNoteResp)
	err := c.cc.Invoke(ctx, InteractionService_CommentOnNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCommentResp)
	err := c.cc.Invoke(ctx, InteractionService_DeleteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionServiceClient) GetNoteInteractions(ctx context.Context, in *GetNoteInteractionsReq, opts ...grpc.CallOption) (*GetNoteInteractionsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNoteInteractionsResp)
	err := c.cc.Invoke(ctx, InteractionService_GetNoteInteractions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InteractionServiceServer is the server API for InteractionService service.
// All implementations must embed UnimplementedInteractionServiceServer
// for forward compatibility.
//
// ──────────── 互动服务 ────────────
type InteractionServiceServer interface {
	LikeNote(context.Context, *LikeNoteReq) (*LikeNoteResp, error)
	UnlikeNote(context.Context, *UnlikeNoteReq) (*UnlikeNoteResp, error)
	CollectNote(context.Context, *CollectNoteReq) (*CollectNoteResp, error)
	UncollectNote(context.Context, *UncollectNoteReq) (*UncollectNoteResp, error)
	CommentOnNote(context.Context, *CommentOnNoteReq) (*CommentOnNoteResp, error)
	DeleteComment(context.Context, *DeleteCommentReq) (*DeleteCommentResp, error)
	GetNoteInteractions(context.Context, *GetNoteInteractionsReq) (*GetNoteInteractionsResp, error)
	mustEmbedUnimplementedInteractionServiceServer()
}

// UnimplementedInteractionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInteractionServiceServer struct{}

func (UnimplementedInteractionServiceServer) LikeNote(context.Context, *LikeNoteReq) (*LikeNoteResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LikeNote not implemented")
}
func (UnimplementedInteractionServiceServer) UnlikeNote(context.Context, *UnlikeNoteReq) (*UnlikeNoteResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlikeNote not implemented")
}
func (UnimplementedInteractionServiceServer) CollectNote(context.Context, *CollectNoteReq) (*CollectNoteResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectNote not implemented")
}
func (UnimplementedInteractionServiceServer) UncollectNote(context.Context, *UncollectNoteReq) (*UncollectNoteResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UncollectNote not implemented")
}
func (UnimplementedInteractionServiceServer) CommentOnNote(context.Context, *CommentOnNoteReq) (*CommentOnNoteResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CommentOnNote not implemented")
}
func (UnimplementedInteractionServiceServer) DeleteComment(context.Context, *DeleteCommentReq) (*DeleteCommentResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedInteractionServiceServer) GetNoteInteractions(context.Context, *GetNoteInteractionsReq) (*GetNoteInteractionsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNoteInteractions not implemented")
}
func (UnimplementedInteractionServiceServer) mustEmbedUnimplementedInteractionServiceServer() {}
func (UnimplementedInteractionServiceServer) testEmbeddedByValue()                            {}

// UnsafeInteractionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InteractionServiceServer will
// result in compilation errors.
type UnsafeInteractionServiceServer interface {
	mustEmbedUnimplementedInteractionServiceServer()
}

func RegisterInteractionServiceServer(s grpc.ServiceRegistrar, srv InteractionServiceServer) {
	// If the following call panics, it indicates UnimplementedInteractionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InteractionService_ServiceDesc, srv)
}

func _InteractionService_LikeNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeNoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).LikeNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_LikeNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).LikeNote(ctx, req.(*LikeNoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_UnlikeNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlikeNoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).UnlikeNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_UnlikeNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).UnlikeNote(ctx, req.(*UnlikeNoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_CollectNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectNoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).CollectNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_CollectNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).CollectNote(ctx, req.(*CollectNoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_UncollectNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UncollectNoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).UncollectNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_UncollectNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).UncollectNote(ctx, req.(*UncollectNoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_CommentOnNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentOnNoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).CommentOnNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_CommentOnNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).CommentOnNote(ctx, req.(*CommentOnNoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_DeleteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).DeleteComment(ctx, req.(*DeleteCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionService_GetNoteInteractions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNoteInteractionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServiceServer).GetNoteInteractions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionService_GetNoteInteractions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServiceServer).GetNoteInteractions(ctx, req.(*GetNoteInteractionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// InteractionService_ServiceDesc is the grpc.ServiceDesc for InteractionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InteractionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "interaction.InteractionService",
	HandlerType: (*InteractionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LikeNote",
			Handler:    _InteractionService_LikeNote_Handler,
		},
		{
			MethodName: "UnlikeNote",
			Handler:    _InteractionService_UnlikeNote_Handler,
		},
		{
			MethodName: "CollectNote",
			Handler:    _InteractionService_CollectNote_Handler,
		},
		{
			MethodName: "UncollectNote",
			Handler:    _InteractionService_UncollectNote_Handler,
		},
		{
			MethodName: "CommentOnNote",
			Handler:    _InteractionService_CommentOnNote_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _InteractionService_DeleteComment_Handler,
		},
		{
			MethodName: "GetNoteInteractions",
			Handler:    _InteractionService_GetNoteInteractions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interaction/interaction.proto",
}
