// proto/interaction/interaction.proto
// 互动服务 Protobuf 定义。
// 定义点赞、收藏、评论及互动汇总查询接口。
// 生成 Go 桩代码：make proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: interaction/interaction.proto

package interactionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LikeNoteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NoteId        int64                  `protobuf:"varint,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeNoteReq) Reset() {
	*x = LikeNoteReq{}
	mi := &file_interaction_interaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeNoteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeNoteReq) ProtoMessage() {}

func (x *LikeNoteReq) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeNoteReq.ProtoReflect.Descriptor instead.
func (*LikeNoteReq) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{0}
}

func (x *LikeNoteReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikeNoteReq) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

type LikeNoteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeNoteResp) Reset() {
	*x = LikeNoteResp{}
	mi := &file_interaction_interaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeNoteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeNoteResp) ProtoMessage() {}

func (x *LikeNoteResp) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeNoteResp.ProtoReflect.Descriptor instead.
func (*LikeNoteResp) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{1}
}

func (x *LikeNoteResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type UnlikeNoteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NoteId        int64                  `protobuf:"varint,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeNoteReq) Reset() {
	*x = UnlikeNoteReq{}
	mi := &file_interaction_interaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeNoteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeNoteReq) ProtoMessage() {}

func (x *UnlikeNoteReq) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeNoteReq.ProtoReflect.Descriptor instead.
func (*UnlikeNoteReq) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{2}
}

func (x *UnlikeNoteReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnlikeNoteReq) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

type UnlikeNoteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeNoteResp) Reset() {
	*x = UnlikeNoteResp{}
	mi := &file_interaction_interaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeNoteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeNoteResp) ProtoMessage() {}

func (x *UnlikeNoteResp) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeNoteResp.ProtoReflect.Descriptor instead.
func (*UnlikeNoteResp) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{3}
}

func (x *UnlikeNoteResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type CollectNoteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NoteId        int64                  `protobuf:"varint,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectNoteReq) Reset() {
	*x = CollectNoteReq{}
	mi := &file_interaction_interaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectNoteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectNoteReq) ProtoMessage() {}

func (x *CollectNoteReq) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectNoteReq.ProtoReflect.Descriptor instead.
func (*CollectNoteReq) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{4}
}

func (x *CollectNoteReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CollectNoteReq) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

type CollectNoteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectNoteResp) Reset() {
	*x = CollectNoteResp{}
	mi := &file_interaction_interaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectNoteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectNoteResp) ProtoMessage() {}

func (x *CollectNoteResp) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectNoteResp.ProtoReflect.Descriptor instead.
func (*CollectNoteResp) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{5}
}

func (x *CollectNoteResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type UncollectNoteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NoteId        int64                  `protobuf:"varint,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UncollectNoteReq) Reset() {
	*x = UncollectNoteReq{}
	mi := &file_interaction_interaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UncollectNoteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UncollectNoteReq) ProtoMessage() {}

func (x *UncollectNoteReq) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UncollectNoteReq.ProtoReflect.Descriptor instead.
func (*UncollectNoteReq) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{6}
}

func (x *UncollectNoteReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UncollectNoteReq) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

type UncollectNoteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UncollectNoteResp) Reset() {
	*x = UncollectNoteResp{}
	mi := &file_interaction_interaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UncollectNoteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UncollectNoteResp) ProtoMessage() {}

func (x *UncollectNoteResp) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UncollectNoteResp.ProtoReflect.Descriptor instead.
func (*UncollectNoteResp) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{7}
}

func (x *UncollectNoteResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type CommentOnNoteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NoteId        int64                  `protobuf:"varint,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ParentId      int64                  `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // 回复某条评论，顶层为 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentOnNoteReq) Reset() {
	*x = CommentOnNoteReq{}
	mi := &file_interaction_interaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentOnNoteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentOnNoteReq) ProtoMessage() {}

func (x *CommentOnNoteReq) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentOnNoteReq.ProtoReflect.Descriptor instead.
func (*CommentOnNoteReq) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{8}
}

func (x *CommentOnNoteReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommentOnNoteReq) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *CommentOnNoteReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentOnNoteReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

type CommentOnNoteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     int64                  `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentOnNoteResp) Reset() {
	*x = CommentOnNoteResp{}
	mi := &file_interaction_interaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentOnNoteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentOnNoteResp) ProtoMessage() {}

func (x *CommentOnNoteResp) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentOnNoteResp.ProtoReflect.Descriptor instead.
func (*CommentOnNoteResp) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{9}
}

func (x *CommentOnNoteResp) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type DeleteCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     int64                  `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentReq) Reset() {
	*x = DeleteCommentReq{}
	mi := &file_interaction_interaction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentReq) ProtoMessage() {}

func (x *DeleteCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentReq.ProtoReflect.Descriptor instead.
func (*DeleteCommentReq) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteCommentReq) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *DeleteCommentReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentResp) Reset() {
	*x = DeleteCommentResp{}
	mi := &file_interaction_interaction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResp) ProtoMessage() {}

func (x *DeleteCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResp.ProtoReflect.Descriptor instead.
func (*DeleteCommentResp) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteCommentResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetNoteInteractionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        int64                  `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 当前用户（用于判断是否已点赞/收藏）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoteInteractionsReq) Reset() {
	*x = GetNoteInteractionsReq{}
	mi := &file_interaction_interaction_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoteInteractionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteInteractionsReq) ProtoMessage() {}

func (x *GetNoteInteractionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteInteractionsReq.ProtoReflect.Descriptor instead.
func (*GetNoteInteractionsReq) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{12}
}

func (x *GetNoteInteractionsReq) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *GetNoteInteractionsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CommentItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	ParentId      int64                  `protobuf:"varint,6,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentItem) Reset() {
	*x = CommentItem{}
	mi := &file_interaction_interaction_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentItem) ProtoMessage() {}

func (x *CommentItem) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentItem.ProtoReflect.Descriptor instead.
func (*CommentItem) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{13}
}

func (x *CommentItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommentItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommentItem) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CommentItem) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *CommentItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentItem) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CommentItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetNoteInteractionsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LikeCount     int64                  `protobuf:"varint,1,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CollectCount  int64                  `protobuf:"varint,2,opt,name=collect_count,json=collectCount,proto3" json:"collect_count,omitempty"`
	CommentCount  int64                  `protobuf:"varint,3,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	IsLiked       bool                   `protobuf:"varint,4,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`             // 当前用户是否已点赞
	IsCollected   bool                   `protobuf:"varint,5,opt,name=is_collected,json=isCollected,proto3" json:"is_collected,omitempty"` // 当前用户是否已收藏
	Comments      []*CommentItem         `protobuf:"bytes,6,rep,name=comments,proto3" json:"comments,omitempty"`                           // 评论列表（默认最新 10 条）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoteInteractionsResp) Reset() {
	*x = GetNoteInteractionsResp{}
	mi := &file_interaction_interaction_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoteInteractionsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteInteractionsResp) ProtoMessage() {}

func (x *GetNoteInteractionsResp) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_interaction_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteInteractionsResp.ProtoReflect.Descriptor instead.
func (*GetNoteInteractionsResp) Descriptor() ([]byte, []int) {
	return file_interaction_interaction_proto_rawDescGZIP(), []int{14}
}

func (x *GetNoteInteractionsResp) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *GetNoteInteractionsResp) GetCollectCount() int64 {
	if x != nil {
		return x.CollectCount
	}
	return 0
}

func (x *GetNoteInteractionsResp) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *GetNoteInteractionsResp) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

func (x *GetNoteInteractionsResp) GetIsCollected() bool {
	if x != nil {
		return x.IsCollected
	}
	return false
}

func (x *GetNoteInteractionsResp) GetComments() []*CommentItem {
	if x != nil {
		return x.Comments
	}
	return nil
}

var File_interaction_interaction_proto protoreflect.FileDescriptor

const file_interaction_interaction_proto_rawDesc = "" +
	"\n" +
	"\x1dinteraction/interaction.proto\x12\vinteraction\"?\n" +
	"\vLikeNoteReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\x03R\x06noteId\"\x1e\n" +
	"\fLikeNoteResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"A\n" +
	"\rUnlikeNoteReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\x03R\x06noteId\" \n" +
	"\x0eUnlikeNoteResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"B\n" +
	"\x0eCollectNoteReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\x03R\x06noteId\"!\n" +
	"\x0fCollectNoteResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"D\n" +
	"\x10UncollectNoteReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\x03R\x06noteId\"#\n" +
	"\x11UncollectNoteResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"{\n" +
	"\x10CommentOnNoteReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\x03R\x06noteId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\x03R\bparentId\"2\n" +
	"\x11CommentOnNoteResp\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x03R\tcommentId\"J\n" +
	"\x10DeleteCommentReq\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x03R\tcommentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"#\n" +
	"\x11DeleteCommentResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"J\n" +
	"\x16GetNoteInteractionsReq\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x03R\x06noteId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\xc0\x01\n" +
	"\vCommentItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1b\n" +
	"\tparent_id\x18\x06 \x01(\x03R\bparentId\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"\xf6\x01\n" +
	"\x17GetNoteInteractionsResp\x12\x1d\n" +
	"\n" +
	"like_count\x18\x01 \x01(\x03R\tlikeCount\x12#\n" +
	"\rcollect_count\x18\x02 \x01(\x03R\fcollectCount\x12#\n" +
	"\rcomment_count\x18\x03 \x01(\x03R\fcommentCount\x12\x19\n" +
	"\bis_liked\x18\x04 \x01(\bR\aisLiked\x12!\n" +
	"\fis_collected\x18\x05 \x01(\bR\visCollected\x124\n" +
	"\bcomments\x18\x06 \x03(\v2\x18.interaction.CommentItemR\bcomments2\xb8\x04\n" +
	"\x12InteractionService\x12?\n" +
	"\bLikeNote\x12\x18.interaction.LikeNoteReq\x1a\x19.interaction.LikeNoteResp\x12E\n" +
	"\n" +
	"UnlikeNote\x12\x1a.interaction.UnlikeNoteReq\x1a\x1b.interaction.UnlikeNoteResp\x12H\n" +
	"\vCollectNote\x12\x1b.interaction.CollectNoteReq\x1a\x1c.interaction.CollectNoteResp\x12N\n" +
	"\rUncollectNote\x12\x1d.interaction.UncollectNoteReq\x1a\x1e.interaction.UncollectNoteResp\x12N\n" +
	"\rCommentOnNote\x12\x1d.interaction.CommentOnNoteReq\x1a\x1e.interaction.CommentOnNoteResp\x12N\n" +
	"\rDeleteComment\x12\x1d.interaction.DeleteCommentReq\x1a\x1e.interaction.DeleteCommentResp\x12`\n" +
	"\x13GetNoteInteractions\x12#.interaction.GetNoteInteractionsReq\x1a$.interaction.GetNoteInteractionsRespB+Z)xys-clone/proto/interaction;interactionpbb\x06proto3"

var (
	file_interaction_interaction_proto_rawDescOnce sync.Once
	file_interaction_interaction_proto_rawDescData []byte
)

func file_interaction_interaction_proto_rawDescGZIP() []byte {
	file_interaction_interaction_proto_rawDescOnce.Do(func() {
		file_interaction_interaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_interaction_interaction_proto_rawDesc), len(file_interaction_interaction_proto_rawDesc)))
	})
	return file_interaction_interaction_proto_rawDescData
}

var file_interaction_interaction_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_interaction_interaction_proto_goTypes = []any{
	(*LikeNoteReq)(nil),             // 0: interaction.LikeNoteReq
	(*LikeNoteResp)(nil),            // 1: interaction.LikeNoteResp
	(*UnlikeNoteReq)(nil),           // 2: interaction.UnlikeNoteReq
	(*UnlikeNoteResp)(nil),          // 3: interaction.UnlikeNoteResp
	(*CollectNoteReq)(nil),          // 4: interaction.CollectNoteReq
	(*CollectNoteResp)(nil),         // 5: interaction.CollectNoteResp
	(*UncollectNoteReq)(nil),        // 6: interaction.UncollectNoteReq
	(*UncollectNoteResp)(nil),       // 7: interaction.UncollectNoteResp
	(*CommentOnNoteReq)(nil),        // 8: interaction.CommentOnNoteReq
	(*CommentOnNoteResp)(nil),       // 9: interaction.CommentOnNoteResp
	(*DeleteCommentReq)(nil),        // 10: interaction.DeleteCommentReq
	(*DeleteCommentResp)(nil),       // 11: interaction.DeleteCommentResp
	(*GetNoteInteractionsReq)(nil),  // 12: interaction.GetNoteInteractionsReq
	(*CommentItem)(nil),             // 13: interaction.CommentItem
	(*GetNoteInteractionsResp)(nil), // 14: interaction.GetNoteInteractionsResp
}
var file_interaction_interaction_proto_depIdxs = []int32{
	13, // 0: interaction.GetNoteInteractionsResp.comments:type_name -> interaction.CommentItem
	0,  // 1: interaction.InteractionService.LikeNote:input_type -> interaction.LikeNoteReq
	2,  // 2: interaction.InteractionService.UnlikeNote:input_type -> interaction.UnlikeNoteReq
	4,  // 3: interaction.InteractionService.CollectNote:input_type -> interaction.CollectNoteReq
	6,  // 4: interaction.InteractionService.UncollectNote:input_type -> interaction.UncollectNoteReq
	8,  // 5: interaction.InteractionService.CommentOnNote:input_type -> interaction.CommentOnNoteReq
	10, // 6: interaction.InteractionService.DeleteComment:input_type -> interaction.DeleteCommentReq
	12, // 7: interaction.InteractionService.GetNoteInteractions:input_type -> interaction.GetNoteInteractionsReq
	1,  // 8: interaction.InteractionService.LikeNote:output_type -> interaction.LikeNoteResp
	3,  // 9: interaction.InteractionService.UnlikeNote:output_type -> interaction.UnlikeNoteResp
	5,  // 10: interaction.InteractionService.CollectNote:output_type -> interaction.CollectNoteResp
	7,  // 11: interaction.InteractionService.UncollectNote:output_type -> interaction.UncollectNoteResp
	9,  // 12: interaction.InteractionService.CommentOnNote:output_type -> interaction.CommentOnNoteResp
	11, // 13: interaction.InteractionService.DeleteComment:output_type -> interaction.DeleteCommentResp
	14, // 14: interaction.InteractionService.GetNoteInteractions:output_type -> interaction.GetNoteInteractionsResp
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_interaction_interaction_proto_init() }
func file_interaction_interaction_proto_init() {
	if File_interaction_interaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_interaction_interaction_proto_rawDesc), len(file_interaction_interaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_interaction_interaction_proto_goTypes,
		DependencyIndexes: file_interaction_interaction_proto_depIdxs,
		MessageInfos:      file_interaction_interaction_proto_msgTypes,
	}.Build()
	File_interaction_interaction_proto = out.File
	file_interaction_interaction_proto_goTypes = nil
	file_interaction_interaction_proto_depIdxs = nil
}
