// proto/agent/agent.proto
// Agent 分析服务 Protobuf 定义。
// 提供粉丝增长分析、标签分析、运营建议。
// 生成 Go 桩代码：make proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: agent/agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNoteFansGrowthReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        int64                  `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoteFansGrowthReq) Reset() {
	*x = GetNoteFansGrowthReq{}
	mi := &file_agent_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoteFansGrowthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteFansGrowthReq) ProtoMessage() {}

func (x *GetNoteFansGrowthReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteFansGrowthReq.ProtoReflect.Descriptor instead.
func (*GetNoteFansGrowthReq) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{0}
}

func (x *GetNoteFansGrowthReq) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

type FansGrowthPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hour          string                 `protobuf:"bytes,1,opt,name=hour,proto3" json:"hour,omitempty"`    // 格式 "2026-07-06T08"（按小时）
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // 该小时新增粉丝
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FansGrowthPoint) Reset() {
	*x = FansGrowthPoint{}
	mi := &file_agent_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FansGrowthPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FansGrowthPoint) ProtoMessage() {}

func (x *FansGrowthPoint) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FansGrowthPoint.ProtoReflect.Descriptor instead.
func (*FansGrowthPoint) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{1}
}

func (x *FansGrowthPoint) GetHour() string {
	if x != nil {
		return x.Hour
	}
	return ""
}

func (x *FansGrowthPoint) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetNoteFansGrowthResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*FansGrowthPoint     `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoteFansGrowthResp) Reset() {
	*x = GetNoteFansGrowthResp{}
	mi := &file_agent_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoteFansGrowthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteFansGrowthResp) ProtoMessage() {}

func (x *GetNoteFansGrowthResp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteFansGrowthResp.ProtoReflect.Descriptor instead.
func (*GetNoteFansGrowthResp) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{2}
}

func (x *GetNoteFansGrowthResp) GetPoints() []*FansGrowthPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type GetTagAnalyticsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagAnalyticsReq) Reset() {
	*x = GetTagAnalyticsReq{}
	mi := &file_agent_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagAnalyticsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagAnalyticsReq) ProtoMessage() {}

func (x *GetTagAnalyticsReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagAnalyticsReq.ProtoReflect.Descriptor instead.
func (*GetTagAnalyticsReq) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{3}
}

func (x *GetTagAnalyticsReq) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type GetTagAnalyticsResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Tag            string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	NoteCount      int64                  `protobuf:"varint,2,opt,name=note_count,json=noteCount,proto3" json:"note_count,omitempty"` // 使用该标签的笔记数
	TotalLikes     int64                  `protobuf:"varint,3,opt,name=total_likes,json=totalLikes,proto3" json:"total_likes,omitempty"`
	TotalCollects  int64                  `protobuf:"varint,4,opt,name=total_collects,json=totalCollects,proto3" json:"total_collects,omitempty"`
	TotalComments  int64                  `protobuf:"varint,5,opt,name=total_comments,json=totalComments,proto3" json:"total_comments,omitempty"`
	EngagementRate float64                `protobuf:"fixed64,6,opt,name=engagement_rate,json=engagementRate,proto3" json:"engagement_rate,omitempty"` // 互动率 = (likes+collects+comments) / note_count
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTagAnalyticsResp) Reset() {
	*x = GetTagAnalyticsResp{}
	mi := &file_agent_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagAnalyticsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagAnalyticsResp) ProtoMessage() {}

func (x *GetTagAnalyticsResp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagAnalyticsResp.ProtoReflect.Descriptor instead.
func (*GetTagAnalyticsResp) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{4}
}

func (x *GetTagAnalyticsResp) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *GetTagAnalyticsResp) GetNoteCount() int64 {
	if x != nil {
		return x.NoteCount
	}
	return 0
}

func (x *GetTagAnalyticsResp) GetTotalLikes() int64 {
	if x != nil {
		return x.TotalLikes
	}
	return 0
}

func (x *GetTagAnalyticsResp) GetTotalCollects() int64 {
	if x != nil {
		return x.TotalCollects
	}
	return 0
}

func (x *GetTagAnalyticsResp) GetTotalComments() int64 {
	if x != nil {
		return x.TotalComments
	}
	return 0
}

func (x *GetTagAnalyticsResp) GetEngagementRate() float64 {
	if x != nil {
		return x.EngagementRate
	}
	return 0
}

type GetTopTagsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // 默认 10
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopTagsReq) Reset() {
	*x = GetTopTagsReq{}
	mi := &file_agent_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopTagsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopTagsReq) ProtoMessage() {}

func (x *GetTopTagsReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopTagsReq.ProtoReflect.Descriptor instead.
func (*GetTopTagsReq) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{5}
}

func (x *GetTopTagsReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TagSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Tag            string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	NoteCount      int64                  `protobuf:"varint,2,opt,name=note_count,json=noteCount,proto3" json:"note_count,omitempty"`
	EngagementRate float64                `protobuf:"fixed64,3,opt,name=engagement_rate,json=engagementRate,proto3" json:"engagement_rate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TagSummary) Reset() {
	*x = TagSummary{}
	mi := &file_agent_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagSummary) ProtoMessage() {}

func (x *TagSummary) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagSummary.ProtoReflect.Descriptor instead.
func (*TagSummary) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{6}
}

func (x *TagSummary) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *TagSummary) GetNoteCount() int64 {
	if x != nil {
		return x.NoteCount
	}
	return 0
}

func (x *TagSummary) GetEngagementRate() float64 {
	if x != nil {
		return x.EngagementRate
	}
	return 0
}

type GetTopTagsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*TagSummary          `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopTagsResp) Reset() {
	*x = GetTopTagsResp{}
	mi := &file_agent_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopTagsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopTagsResp) ProtoMessage() {}

func (x *GetTopTagsResp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopTagsResp.ProtoReflect.Descriptor instead.
func (*GetTopTagsResp) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{7}
}

func (x *GetTopTagsResp) GetTags() []*TagSummary {
	if x != nil {
		return x.Tags
	}
	return nil
}

type GetSuggestionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSuggestionsReq) Reset() {
	*x = GetSuggestionsReq{}
	mi := &file_agent_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSuggestionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSuggestionsReq) ProtoMessage() {}

func (x *GetSuggestionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSuggestionsReq.ProtoReflect.Descriptor instead.
func (*GetSuggestionsReq) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{8}
}

func (x *GetSuggestionsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetSuggestionsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suggestions   []string               `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"` // 中文建议列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSuggestionsResp) Reset() {
	*x = GetSuggestionsResp{}
	mi := &file_agent_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSuggestionsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSuggestionsResp) ProtoMessage() {}

func (x *GetSuggestionsResp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSuggestionsResp.ProtoReflect.Descriptor instead.
func (*GetSuggestionsResp) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{9}
}

func (x *GetSuggestionsResp) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

var File_agent_agent_proto protoreflect.FileDescriptor

const file_agent_agent_proto_rawDesc = "" +
	"\n" +
	"\x11agent/agent.proto\x12\x05agent\"/\n" +
	"\x14GetNoteFansGrowthReq\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x03R\x06noteId\";\n" +
	"\x0fFansGrowthPoint\x12\x12\n" +
	"\x04hour\x18\x01 \x01(\tR\x04hour\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"G\n" +
	"\x15GetNoteFansGrowthResp\x12.\n" +
	"\x06points\x18\x01 \x03(\v2\x16.agent.FansGrowthPointR\x06points\"&\n" +
	"\x12GetTagAnalyticsReq\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\"\xde\x01\n" +
	"\x13GetTagAnalyticsResp\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x1d\n" +
	"\n" +
	"note_count\x18\x02 \x01(\x03R\tnoteCount\x12\x1f\n" +
	"\vtotal_likes\x18\x03 \x01(\x03R\n" +
	"totalLikes\x12%\n" +
	"\x0etotal_collects\x18\x04 \x01(\x03R\rtotalCollects\x12%\n" +
	"\x0etotal_comments\x18\x05 \x01(\x03R\rtotalComments\x12'\n" +
	"\x0fengagement_rate\x18\x06 \x01(\x01R\x0eengagementRate\"%\n" +
	"\rGetTopTagsReq\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"f\n" +
	"\n" +
	"TagSummary\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x1d\n" +
	"\n" +
	"note_count\x18\x02 \x01(\x03R\tnoteCount\x12'\n" +
	"\x0fengagement_rate\x18\x03 \x01(\x01R\x0eengagementRate\"7\n" +
	"\x0eGetTopTagsResp\x12%\n" +
	"\x04tags\x18\x01 \x03(\v2\x11.agent.TagSummaryR\x04tags\",\n" +
	"\x11GetSuggestionsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"6\n" +
	"\x12GetSuggestionsResp\x12 \n" +
	"\vsuggestions\x18\x01 \x03(\tR\vsuggestions2\xaa\x02\n" +
	"\fAgentService\x12N\n" +
	"\x11GetNoteFansGrowth\x12\x1b.agent.GetNoteFansGrowthReq\x1a\x1c.agent.GetNoteFansGrowthResp\x12H\n" +
	"\x0fGetTagAnalytics\x12\x19.agent.GetTagAnalyticsReq\x1a\x1a.agent.GetTagAnalyticsResp\x129\n" +
	"\n" +
	"GetTopTags\x12\x14.agent.GetTopTagsReq\x1a\x15.agent.GetTopTagsResp\x12E\n" +
	"\x0eGetSuggestions\x12\x18.agent.GetSuggestionsReq\x1a\x19.agent.GetSuggestionsRespB\x1fZ\x1dxys-clone/proto/agent;agentpbb\x06proto3"

var (
	file_agent_agent_proto_rawDescOnce sync.Once
	file_agent_agent_proto_rawDescData []byte
)

func file_agent_agent_proto_rawDescGZIP() []byte {
	file_agent_agent_proto_rawDescOnce.Do(func() {
		file_agent_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_agent_proto_rawDesc), len(file_agent_agent_proto_rawDesc)))
	})
	return file_agent_agent_proto_rawDescData
}

var file_agent_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_agent_agent_proto_goTypes = []any{
	(*GetNoteFansGrowthReq)(nil),  // 0: agent.GetNoteFansGrowthReq
	(*FansGrowthPoint)(nil),       // 1: agent.FansGrowthPoint
	(*GetNoteFansGrowthResp)(nil), // 2: agent.GetNoteFansGrowthResp
	(*GetTagAnalyticsReq)(nil),    // 3: agent.GetTagAnalyticsReq
	(*GetTagAnalyticsResp)(nil),   // 4: agent.GetTagAnalyticsResp
	(*GetTopTagsReq)(nil),         // 5: agent.GetTopTagsReq
	(*TagSummary)(nil),            // 6: agent.TagSummary
	(*GetTopTagsResp)(nil),        // 7: agent.GetTopTagsResp
	(*GetSuggestionsReq)(nil),     // 8: agent.GetSuggestionsReq
	(*GetSuggestionsResp)(nil),    // 9: agent.GetSuggestionsResp
}
var file_agent_agent_proto_depIdxs = []int32{
	1, // 0: agent.GetNoteFansGrowthResp.points:type_name -> agent.FansGrowthPoint
	6, // 1: agent.GetTopTagsResp.tags:type_name -> agent.TagSummary
	0, // 2: agent.AgentService.GetNoteFansGrowth:input_type -> agent.GetNoteFansGrowthReq
	3, // 3: agent.AgentService.GetTagAnalytics:input_type -> agent.GetTagAnalyticsReq
	5, // 4: agent.AgentService.GetTopTags:input_type -> agent.GetTopTagsReq
	8, // 5: agent.AgentService.GetSuggestions:input_type -> agent.GetSuggestionsReq
	2, // 6: agent.AgentService.GetNoteFansGrowth:output_type -> agent.GetNoteFansGrowthResp
	4, // 7: agent.AgentService.GetTagAnalytics:output_type -> agent.GetTagAnalyticsResp
	7, // 8: agent.AgentService.GetTopTags:output_type -> agent.GetTopTagsResp
	9, // 9: agent.AgentService.GetSuggestions:output_type -> agent.GetSuggestionsResp
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_agent_agent_proto_init() }
func file_agent_agent_proto_init() {
	if File_agent_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_agent_proto_rawDesc), len(file_agent_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_agent_proto_goTypes,
		DependencyIndexes: file_agent_agent_proto_depIdxs,
		MessageInfos:      file_agent_agent_proto_msgTypes,
	}.Build()
	File_agent_agent_proto = out.File
	file_agent_agent_proto_goTypes = nil
	file_agent_agent_proto_depIdxs = nil
}
