// proto/agent/agent.proto
// Agent 分析服务 Protobuf 定义。
// 提供粉丝增长分析、标签分析、运营建议。
// 生成 Go 桩代码：make proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: agent/agent.proto

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_GetNoteFansGrowth_FullMethodName = "/agent.AgentService/GetNoteFansGrowth"
	AgentService_GetTagAnalytics_FullMethodName   = "/agent.AgentService/GetTagAnalytics"
	AgentService_GetTopTags_FullMethodName        = "/agent.AgentService/GetTopTags"
	AgentService_GetSuggestions_FullMethodName    = "/agent.AgentService/GetSuggestions"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ──────────── Agent 服务 ────────────
type AgentServiceClient interface {
	GetNoteFansGrowth(ctx context.Context, in *GetNoteFansGrowthReq, opts ...grpc.CallOption) (*GetNoteFansGrowthResp, error)
	GetTagAnalytics(ctx context.Context, in *GetTagAnalyticsReq, opts ...grpc.CallOption) (*GetTagAnalyticsResp, error)
	GetTopTags(ctx context.Context, in *GetTopTagsReq, opts ...grpc.CallOption) (*GetTopTagsResp, error)
	GetSuggestions(ctx context.Context, in *GetSuggestionsReq, opts ...grpc.CallOption) (*GetSuggestionsResp, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) GetNoteFansGrowth(ctx context.Context, in *GetNoteFansGrowthReq, opts ...grpc.CallOption) (*GetNoteFansGrowthResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNoteFansGrowthResp)
	err := c.cc.Invoke(ctx, AgentService_GetNoteFansGrowth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetTagAnalytics(ctx context.Context, in *GetTagAnalyticsReq, opts ...grpc.CallOption) (*GetTagAnalyticsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTagAnalyticsResp)
	err := c.cc.Invoke(ctx, AgentService_GetTagAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetTopTags(ctx context.Context, in *GetTopTagsReq, opts ...grpc.CallOption) (*GetTopTagsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopTagsResp)
	err := c.cc.Invoke(ctx, AgentService_GetTopTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetSuggestions(ctx context.Context, in *GetSuggestionsReq, opts ...grpc.CallOption) (*GetSuggestionsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSuggestionsResp)
	err := c.cc.Invoke(ctx, AgentService_GetSuggestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// ──────────── Agent 服务 ────────────
type AgentServiceServer interface {
	GetNoteFansGrowth(context.Context, *GetNoteFansGrowthReq) (*GetNoteFansGrowthResp, error)
	GetTagAnalytics(context.Context, *GetTagAnalyticsReq) (*GetTagAnalyticsResp, error)
	GetTopTags(context.Context, *GetTopTagsReq) (*GetTopTagsResp, error)
	GetSuggestions(context.Context, *GetSuggestionsReq) (*GetSuggestionsResp, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) GetNoteFansGrowth(context.Context, *GetNoteFansGrowthReq) (*GetNoteFansGrowthResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNoteFansGrowth not implemented")
}
func (UnimplementedAgentServiceServer) GetTagAnalytics(context.Context, *GetTagAnalyticsReq) (*GetTagAnalyticsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTagAnalytics not implemented")
}
func (UnimplementedAgentServiceServer) GetTopTags(context.Context, *GetTopTagsReq) (*GetTopTagsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopTags not implemented")
}
func (UnimplementedAgentServiceServer) GetSuggestions(context.Context, *GetSuggestionsReq) (*GetSuggestionsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSuggestions not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_GetNoteFansGrowth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNoteFansGrowthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetNoteFansGrowth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetNoteFansGrowth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetNoteFansGrowth(ctx, req.(*GetNoteFansGrowthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetTagAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTagAnalyticsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetTagAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetTagAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetTagAnalytics(ctx, req.(*GetTagAnalyticsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetTopTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopTagsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetTopTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetTopTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetTopTags(ctx, req.(*GetTopTagsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetSuggestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSuggestionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetSuggestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetSuggestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetSuggestions(ctx, req.(*GetSuggestionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNoteFansGrowth",
			Handler:    _AgentService_GetNoteFansGrowth_Handler,
		},
		{
			MethodName: "GetTagAnalytics",
			Handler:    _AgentService_GetTagAnalytics_Handler,
		},
		{
			MethodName: "GetTopTags",
			Handler:    _AgentService_GetTopTags_Handler,
		},
		{
			MethodName: "GetSuggestions",
			Handler:    _AgentService_GetSuggestions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent/agent.proto",
}
