// proto/rank/rank.proto
// 排行榜服务 Protobuf 定义。
// 提供热门笔记排行查询。
// 生成 Go 桩代码：make proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: rank/rank.proto

package rankpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHotNotesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"` // 获取条数，默认 20，最大 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHotNotesReq) Reset() {
	*x = GetHotNotesReq{}
	mi := &file_rank_rank_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotNotesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotNotesReq) ProtoMessage() {}

func (x *GetHotNotesReq) ProtoReflect() protoreflect.Message {
	mi := &file_rank_rank_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotNotesReq.ProtoReflect.Descriptor instead.
func (*GetHotNotesReq) Descriptor() ([]byte, []int) {
	return file_rank_rank_proto_rawDescGZIP(), []int{0}
}

func (x *GetHotNotesReq) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RankItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        int64                  `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	AuthorId      int64                  `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	AuthorName    string                 `protobuf:"bytes,3,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	AuthorAvatar  string                 `protobuf:"bytes,4,opt,name=author_avatar,json=authorAvatar,proto3" json:"author_avatar,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	ImageUrls     []string               `protobuf:"bytes,7,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	Tags          []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	HeatScore     float64                `protobuf:"fixed64,10,opt,name=heat_score,json=heatScore,proto3" json:"heat_score,omitempty"` // 热度分
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankItem) Reset() {
	*x = RankItem{}
	mi := &file_rank_rank_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankItem) ProtoMessage() {}

func (x *RankItem) ProtoReflect() protoreflect.Message {
	mi := &file_rank_rank_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankItem.ProtoReflect.Descriptor instead.
func (*RankItem) Descriptor() ([]byte, []int) {
	return file_rank_rank_proto_rawDescGZIP(), []int{1}
}

func (x *RankItem) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *RankItem) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *RankItem) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *RankItem) GetAuthorAvatar() string {
	if x != nil {
		return x.AuthorAvatar
	}
	return ""
}

func (x *RankItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RankItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RankItem) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *RankItem) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RankItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *RankItem) GetHeatScore() float64 {
	if x != nil {
		return x.HeatScore
	}
	return 0
}

type GetHotNotesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*RankItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHotNotesResp) Reset() {
	*x = GetHotNotesResp{}
	mi := &file_rank_rank_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotNotesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotNotesResp) ProtoMessage() {}

func (x *GetHotNotesResp) ProtoReflect() protoreflect.Message {
	mi := &file_rank_rank_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotNotesResp.ProtoReflect.Descriptor instead.
func (*GetHotNotesResp) Descriptor() ([]byte, []int) {
	return file_rank_rank_proto_rawDescGZIP(), []int{2}
}

func (x *GetHotNotesResp) GetItems() []*RankItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_rank_rank_proto protoreflect.FileDescriptor

const file_rank_rank_proto_rawDesc = "" +
	"\n" +
	"\x0frank/rank.proto\x12\x04rank\"&\n" +
	"\x0eGetHotNotesReq\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"\xa7\x02\n" +
	"\bRankItem\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x03R\x06noteId\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\x03R\bauthorId\x12\x1f\n" +
	"\vauthor_name\x18\x03 \x01(\tR\n" +
	"authorName\x12#\n" +
	"\rauthor_avatar\x18\x04 \x01(\tR\fauthorAvatar\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"image_urls\x18\a \x03(\tR\timageUrls\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"heat_score\x18\n" +
	" \x01(\x01R\theatScore\"7\n" +
	"\x0fGetHotNotesResp\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.rank.RankItemR\x05items2I\n" +
	"\vRankService\x12:\n" +
	"\vGetHotNotes\x12\x14.rank.GetHotNotesReq\x1a\x15.rank.GetHotNotesRespB\x1dZ\x1bxys-clone/proto/rank;rankpbb\x06proto3"

var (
	file_rank_rank_proto_rawDescOnce sync.Once
	file_rank_rank_proto_rawDescData []byte
)

func file_rank_rank_proto_rawDescGZIP() []byte {
	file_rank_rank_proto_rawDescOnce.Do(func() {
		file_rank_rank_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rank_rank_proto_rawDesc), len(file_rank_rank_proto_rawDesc)))
	})
	return file_rank_rank_proto_rawDescData
}

var file_rank_rank_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rank_rank_proto_goTypes = []any{
	(*GetHotNotesReq)(nil),  // 0: rank.GetHotNotesReq
	(*RankItem)(nil),        // 1: rank.RankItem
	(*GetHotNotesResp)(nil), // 2: rank.GetHotNotesResp
}
var file_rank_rank_proto_depIdxs = []int32{
	1, // 0: rank.GetHotNotesResp.items:type_name -> rank.RankItem
	0, // 1: rank.RankService.GetHotNotes:input_type -> rank.GetHotNotesReq
	2, // 2: rank.RankService.GetHotNotes:output_type -> rank.GetHotNotesResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rank_rank_proto_init() }
func file_rank_rank_proto_init() {
	if File_rank_rank_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rank_rank_proto_rawDesc), len(file_rank_rank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rank_rank_proto_goTypes,
		DependencyIndexes: file_rank_rank_proto_depIdxs,
		MessageInfos:      file_rank_rank_proto_msgTypes,
	}.Build()
	File_rank_rank_proto = out.File
	file_rank_rank_proto_goTypes = nil
	file_rank_rank_proto_depIdxs = nil
}
