// proto/rank/rank.proto
// 排行榜服务 Protobuf 定义。
// 提供热门笔记排行查询。
// 生成 Go 桩代码：make proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: rank/rank.proto

package rankpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RankService_GetHotNotes_FullMethodName = "/rank.RankService/GetHotNotes"
)

// RankServiceClient is the client API for RankService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ──────────── 排行榜服务 ────────────
type RankServiceClient interface {
	// 获取热门笔记 Top N
	GetHotNotes(ctx context.Context, in *GetHotNotesReq, opts ...grpc.CallOption) (*GetHotNotesResp, error)
}

type rankServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRankServiceClient(cc grpc.ClientConnInterface) RankServiceClient {
	return &rankServiceClient{cc}
}

func (c *rankServiceClient) GetHotNotes(ctx context.Context, in *GetHotNotesReq, opts ...grpc.CallOption) (*GetHotNotesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHotNotesResp)
	err := c.cc.Invoke(ctx, RankService_GetHotNotes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RankServiceServer is the server API for RankService service.
// All implementations must embed UnimplementedRankServiceServer
// for forward compatibility.
//
// ──────────── 排行榜服务 ────────────
type RankServiceServer interface {
	// 获取热门笔记 Top N
	GetHotNotes(context.Context, *GetHotNotesReq) (*GetHotNotesResp, error)
	mustEmbedUnimplementedRankServiceServer()
}

// UnimplementedRankServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRankServiceServer struct{}

func (UnimplementedRankServiceServer) GetHotNotes(context.Context, *GetHotNotesReq) (*GetHotNotesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHotNotes not implemented")
}
func (UnimplementedRankServiceServer) mustEmbedUnimplementedRankServiceServer() {}
func (UnimplementedRankServiceServer) testEmbeddedByValue()                     {}

// UnsafeRankServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RankServiceServer will
// result in compilation errors.
type UnsafeRankServiceServer interface {
	mustEmbedUnimplementedRankServiceServer()
}

func RegisterRankServiceServer(s grpc.ServiceRegistrar, srv RankServiceServer) {
	// If the following call panics, it indicates UnimplementedRankServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RankService_ServiceDesc, srv)
}

func _RankService_GetHotNotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHotNotesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankServiceServer).GetHotNotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankService_GetHotNotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankServiceServer).GetHotNotes(ctx, req.(*GetHotNotesReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RankService_ServiceDesc is the grpc.ServiceDesc for RankService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RankService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rank.RankService",
	HandlerType: (*RankServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHotNotes",
			Handler:    _RankService_GetHotNotes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rank/rank.proto",
}
